### ISSUE TITLE
Cognito Identity un-authenticated users example

### ISSUE THREAD

**Issue by komushi** [kmamykin/aws-mqtt#1]
This is a request/question instead of an issue. I was wondering how to use this with Cognito Identity un-authenticated approach. Could you provide a simple example?

**Comment by kmamykin** [comment]
Hi, sorry it took some time to get back to this issue. I added a section in readme:
https://github.com/kmamykin/aws-mqtt#quick-example-using-cognito-identity-un-authenticated-users-approach
