### ISSUE TITLE
Issue with last will message

### ISSUE THREAD

**Issue by Rajnishkumar184** [kmamykin/aws-mqtt#19]
Hi,
I have used this module for AWS mqtt iot connection, but the lwt topic inside will that we passed in AWSMqtt.connect() method is not calling when we turn off the device or network disconnect.

Below is the code snippet:

var AWS = require('aws-sdk');
var AWSMqtt = require('aws-mqtt');

var params = {
    IdentityPoolId: 'xxxxxx-xxxxx-xxxxxxx'
 };

cognitoService=Utils.mqttSetup();
cognitoService.getId(params, function (err, data) {
   CONFIG.IdentityId = data.IdentityId;
});

AWS.config.region = 'xx-xxxx-x';
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
  IdentityId: CONFIG.IdentityId
});

var mqttClient = AWSMqtt.connect({
            WebSocket: window.WebSocket,
            region: AWS.config.region,
            credentials: AWS.config.credentials,
            endpoint: 'xxxxxxxxxx.iot.xxxxxxxx',
            clientId: 'mqttjs_' + (Math.floor((Math.random() * 100000) + 1)),
            will: {
                topic: '/lwt',
                payload: 'hello',
                qos:    0,
                retain: false
            }
        });

**Comment by kmamykin** [comment]
New release 1.0.0 was published allowing `will` option
