### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by cgood92** [kmamykin/aws-mqtt#5]
There is a memory leak problem here.  I'm not sure why it's happening.  Here's what's going on.

I have been logging events emitted, and every several seconds, I'm receiving an "offline" event.  I've been trying to figure it out.  It is causing the MQTT client to reconnect.  But, it's in the reconnect that we have issues.

Every time you reconnect, it creates another client listener.  This creates an exponential problem.

For instance, here's some debugging:

https://github.com/kmamykin/aws-mqtt/blob/be0ad599583c07b18c3f3e3c706fbbb3efc61649/src/Client.js#L8

In this `super()` method, this callback get's called every time it tries to reconnect.  This is creating a lot of listeners.

Right now, from the client created, I'm doing some debugging like:

```
client.on('packetReceive', () => console.log('packetReceive'))
```

Every reconnect, the number of these messages grows exponentially.

**Comment by cgood92** [comment]
After looking through the `mqtt` library that this is extending, it looks like the first parameter of the `super` (the callback) is called under a few different scenarios.  That's fine.  What we should just do is that in `createWebSocketStream`, before you create a new Websocket, you should clean up the old websocket that was created.

**Comment by kmamykin** [comment]
I will take a look at this over the weekend. Feel free to submit a PR if you already have this fixed.
Thanks!

**Comment by cgood92** [comment]
I take it back.  It was my fault.  I had 2 issues:

1. I wasn't cleaning up event listeners
2. I misunderstood just how critical `clientId` uniqueness must be per client (I was thinking "per user", but that was wrong - per client is the correct terminology).  That was pointed out in the README, but I misunderstood it.

So, I have made this MR with my 2 issues documented, in hopes to help other people not have this same problem: https://github.com/kmamykin/aws-mqtt/pull/6.

The solution I pointed out above does not seem to fix anything real, so I say we leave it as it is.

Thanks,

**Comment by RelaxLiu** [comment]
@cgood92 @kmamykin 
After the net is broken, it is reconnected, but there is no data.

publish-subscribe

Subscribe to success

Data reception success

Off the net

Link offline

Reopen the network

After that, the link has been successful. Close, offlin, connection is successful, close, offline has been circulating, neither resubscribe nor cancel subscription.

Want to ask what you need to set up to continue the data transfer
![image](https://user-images.githubusercontent.com/16301089/35659156-b4cf2d64-073f-11e8-98b2-2ab38db25de8.png)
