### ISSUE TITLE
Make the `will` parameter works  to send a message by the broker automatically when the client disconnect badly

### ISSUE THREAD

**Issue by coderade** [kmamykin/aws-mqtt#7]
On the [MQTT](https://github.com/mqttjs/MQTT.js) doc, we have the option to use the `will` parameter to send a message by the broker automatically when the client disconnect badly.

I'm trying to make this work with `aws-mqtt`, but I can't.

My client example:

 ```
const client = AWSMqtt.connect({
  WebSocket: WebSocket,
  region: AWS.config.region,
  credentials: AWS.config.credentials,
  endpoint: config.aws.iot.endpoint,
  clientId: 'mqtt-time-publisher-' + (Math.floor((Math.random() * 100000) + 1)),
  will: {
        topic: `MY-TOPIC`,
        payload: 'disconected',
        qos: 0,
        retain: false
      }
})
```
Is there any way to do this works?

**Comment by kmamykin** [comment]
Apologies for a late response. Not all properties are passed through to Mqtt client. This is an omission, and I will work on fixing it in the next release.

**Comment by coderade** [comment]
I can work on this this weekend and submit a PR if everything works fine.

**Comment by coderade** [comment]
Hi there, I created a PR to solve this issue, the PR #10.  I think it’d be worthwhile to pull it into the project repository in order to get it into the next release of the aws-mqtt library.

Thanks!
