### ISSUE TITLE
The problem of reconnection of web end network

### ISSUE THREAD

**Issue by RelaxLiu** [kmamykin/aws-mqtt#8]
How do you do? I'd like to ask you a question.

When using aws-mqtt, the browser closes the network. When we open the network again, we can see that the information displayed on the console has been linked, closed, offline, linked, closed and offline, and it has been recycled. I want to ask how to solve such a problem.

I look forward to your answer and thank you first.
![image](https://user-images.githubusercontent.com/16301089/35664015-1a9f5c5c-075b-11e8-96fb-36d1759b3f6d.png)

**Comment by RelaxLiu** [comment]
@kmamykin

**Comment by kmamykin** [comment]
I am not sure I follow. Can you post a minimum example that exhibits the problem somewhere?

**Comment by kmamykin** [comment]
This must be fixed on master, will release a new version soon
