### ISSUE TITLE
Signed URLs always last 24h, not 15s as intended

### ISSUE THREAD

**Issue by jonmellman** [kmamykin/aws-mqtt#9]
aws-mqtt passes an [`expiration`](https://github.com/kmamykin/aws-mqtt/blob/master/src/createUrlSigner.js#L16) parameter to aws-signature-v4, but aws-signature-v4 expects an [`expires`](https://github.com/department-stockholm/aws-signature-v4/blob/master/index.js#L84) parameter and defaults to 24h if it doesn't exist.

This is also apparent in the URLs that aws-mqtt generates. There's always a `X-Amz-Expires=86400` (86400s = 24h).

**Comment by kmamykin** [comment]
Thanks for bringing this up. Clearly a bug. Will work on fixing it, unless you beat me to it by submitting a PR :)

**Comment by kmamykin** [comment]
This has been fixed in 00a711c
